import os
from flask import Flask, request, session, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager, current_user
from flask_babel import Babel
from flask_wtf.csrf import CSRFProtect
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from flask_compress import Compress
from config import Config, data_dir

db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_view = 'auth.login'
babel = Babel()
csrf = CSRFProtect()
limiter = Limiter(key_func=get_remote_address, default_limits=[])
compress = Compress()


def get_locale():
	if current_user and current_user.is_authenticated and current_user.language:
		return current_user.language
	return request.accept_languages.best_match(['en', 'de']) or 'en'


def get_timezone():
	if current_user and current_user.is_authenticated and current_user.timezone:
		return current_user.timezone
	return 'UTC'


def create_app(config_class=Config):
	app = Flask(__name__)
	app.config.from_object(config_class)

	os.makedirs(data_dir, exist_ok=True)

	db.init_app(app)
	login_manager.init_app(app)
	babel.init_app(app, locale_selector=get_locale, timezone_selector=get_timezone)
	csrf.init_app(app)
	limiter.init_app(app)
	compress.init_app(app)

	@app.before_request
	def make_session_permanent():
		session.permanent = True

	VERIFY_EXEMPT = {
		'auth.login', 'auth.logout', 'auth.register',
		'auth.verify_email', 'auth.verify_pending', 'auth.resend_verification',
		'static',
	}

	@app.before_request
	def require_email_verification():
		if current_user.is_authenticated and not current_user.email_verified:
			if request.endpoint not in VERIFY_EXEMPT:
				return redirect(url_for('auth.verify_pending'))

	from app.models import User

	@login_manager.user_loader
	def load_user(user_id):
		return db.session.get(User, int(user_id))

	from app.auth import auth_bp
	from app.main import main_bp
	from app.admin import admin_bp
	app.register_blueprint(auth_bp)
	app.register_blueprint(main_bp)
	app.register_blueprint(admin_bp, url_prefix='/admin')

	app.jinja_env.globals['get_now'] = get_now
	app.jinja_env.globals['get_locale'] = get_locale

	@app.template_filter('utc_attr')
	def utc_attr_filter(dt):
		return dt.isoformat() if dt else ''

	@app.context_processor
	def inject_time_warp():
		from app.models import AppSetting
		try:
			setting = db.session.get(AppSetting, 'time_warp')
			if setting and setting.value:
				return {'time_warp_value': setting.value}
		except Exception:
			pass
		return {'time_warp_value': ''}

	@app.errorhandler(404)
	def page_not_found(e):
		return render_template('errors/404.html'), 404

	@app.errorhandler(500)
	def internal_error(e):
		return render_template('errors/500.html'), 500

	with app.app_context():
		try:
			db.create_all()
		except Exception:
			pass  # race condition with multiple gunicorn workers
		_migrate_add_verification_columns()
		_backfill_verified_users()
		seed_matches_if_empty(app)
		_apply_demo_schedule(app)
		_load_persisted_invite_token(app)

	return app


def _migrate_add_verification_columns():
	"""Add email verification columns to existing users table if missing."""
	try:
		cols = [row[1] for row in db.session.execute(db.text("PRAGMA table_info(users)")).fetchall()]
		if 'email_verified' not in cols:
			db.session.execute(db.text("ALTER TABLE users ADD COLUMN email_verified BOOLEAN DEFAULT 1"))
			db.session.execute(db.text("ALTER TABLE users ADD COLUMN verify_token VARCHAR(128)"))
			db.session.execute(db.text("ALTER TABLE users ADD COLUMN verify_sent_at DATETIME"))
			db.session.commit()
	except Exception:
		db.session.rollback()


def _backfill_verified_users():
	"""Mark all existing users as verified (pre-verification-feature users)."""
	from app.models import User
	try:
		updated = User.query.filter_by(email_verified=False).filter(
			User.verify_token.is_(None)
		).update({'email_verified': True})
		if updated:
			db.session.commit()
	except Exception:
		db.session.rollback()


def _apply_demo_schedule(app):
	"""Compress match schedule so all matches happen within hours (for testing)."""
	if not app.config.get('DEMO_SCHEDULE'):
		return
	from app.models import Match, AppSetting
	already = db.session.get(AppSetting, 'demo_schedule_applied')
	if already and already.value == 'true':
		return
	from datetime import datetime, timedelta
	matches = Match.query.order_by(Match.kickoff_utc).all()
	if not matches:
		return
	now = datetime.utcnow()
	interval = timedelta(minutes=15)
	for i, m in enumerate(matches):
		m.kickoff_utc = now + interval * (i + 1)
	setting = AppSetting(key='demo_schedule_applied', value='true')
	db.session.add(setting)
	db.session.commit()
	app.logger.info(f"DEMO_SCHEDULE: compressed {len(matches)} matches starting at {now}")


def _load_persisted_invite_token(app):
	"""Load invite token from DB if it was regenerated by admin."""
	try:
		from app.models import AppSetting
		setting = db.session.get(AppSetting, 'invite_token')
		if setting and setting.value:
			app.config['INVITE_TOKEN'] = setting.value
	except Exception:
		pass


def get_now():
	"""Return current UTC time (naive, no tzinfo -- matches SQLite storage)."""
	from datetime import datetime
	from app.models import AppSetting
	try:
		setting = db.session.get(AppSetting, 'time_warp')
		if setting and setting.value:
			from dateutil import parser
			parsed = parser.isoparse(setting.value)
			return parsed.replace(tzinfo=None)
	except Exception:
		pass
	return datetime.utcnow()


def seed_matches_if_empty(app):
	"""Load match data from JSON into DB if no matches exist."""
	from app.models import Match
	try:
		if Match.query.count() > 0:
			return
	except Exception:
		return

	import json
	from datetime import datetime, timezone, timedelta
	import re

	json_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'data', 'worldcup2026.json')
	if not os.path.exists(json_path):
		app.logger.warning(f"Match data file not found: {json_path}")
		return

	with open(json_path) as f:
		data = json.load(f)

	match_num = 0
	for m in data.get('matches', []):
		match_num += 1

		time_str = m.get('time', '')
		date_str = m.get('date', '')
		utc_offset_match = re.search(r'UTC([+-]\d+)', time_str)
		hour_min = time_str.split(' ')[0] if ' ' in time_str else time_str

		if date_str and hour_min:
			try:
				naive = datetime.strptime(f"{date_str} {hour_min}", "%Y-%m-%d %H:%M")
				offset_hours = int(utc_offset_match.group(1)) if utc_offset_match else 0
				kickoff_utc = naive - timedelta(hours=offset_hours)
				kickoff_utc = kickoff_utc.replace(tzinfo=None)
			except (ValueError, AttributeError):
				kickoff_utc = None
		else:
			kickoff_utc = None

		round_name = m.get('round', '')
		group_name = m.get('group', '')

		is_knockout = round_name in (
			'Round of 32', 'Round of 16', 'Quarter-final',
			'Semi-final', 'Match for third place', 'Final'
		)

		match = Match(
			match_num=m.get('num', match_num),
			round=round_name,
			group_name=group_name,
			kickoff_utc=kickoff_utc,
			team1=m.get('team1', 'TBD'),
			team2=m.get('team2', 'TBD'),
			venue=m.get('ground', ''),
			status='scheduled',
			is_knockout=is_knockout,
		)
		db.session.add(match)

	try:
		db.session.commit()
		app.logger.info(f"Seeded {match_num} matches from worldcup2026.json")
	except Exception:
		db.session.rollback()
		app.logger.info("Match seeding skipped (already seeded by another worker)")
